workflows:
  android-workflow:
    name: Android APK Workflow
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: 3.47.5
    scripts:
      - name: Setup and Build APK
        script: |
          PROJ_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          cd "$PROJ_DIR"
          
          flutter clean
          flutter pub get
          
          # Firebase'in istediği Android ayarını (minSdkVersion 23) zorla dosyaya yazar
          sed -i '' 's/minSdkVersion.*/minSdkVersion 23/g' android/app/build.gradle || sed -i 's/minSdkVersion.*/minSdkVersion 23/g' android/app/build.gradle
          
          # Derlemeyi başlatır
          flutter build apk --release --no-shrink
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
