import 'package:flutter/material.dart';

// ============================================================
// ÇEVİRİLER - Türkçe, İngilizce, Kürtçe
// ============================================================
class Ceviriler {
  static const Map<String, Map<String, String>> _veri = {
    // ==================== TÜRKÇE ====================
    'tr': {
      'app_adi': 'EENApp',
      'alt_baslik': 'Nakliye Pazaryeri',
      'giris_yap': 'Giriş Yap',
      'kayit_ol': 'Kayıt Ol',
      'cikis_yap': 'Çıkış Yap',
      'hesabin_yok': 'Hesabın yok mu? Kayıt ol',
      'hesabin_var': 'Hesabın var mı? Giriş yap',
      'sifremi_unuttum': 'Şifremi unuttum',
      'email': 'E-posta',
      'sifre': 'Şifre',
      'sifre_tekrar': 'Şifre Tekrar',
      'ad_soyad': 'Ad Soyad / Firma Ünvanı',
      'telefon': 'Telefon',
      'hesap_turu': 'Hesap Türü',
      'musteri': 'Müşteri',
      'nakliyeci': 'Nakliyeci',
      'firmalar': 'Firmalar',
      'ilanlar': 'İlanlar',
      'mesajlar': 'Mesajlar',
      'profil': 'Profil',
      'ayarlar': 'Ayarlar',
      'gorunum': 'Görünüm',
      'karanlik_tema': 'Karanlık Tema',
      'dil': 'Dil',
      'turkce': 'Türkçe',
      'ingilizce': 'İngilizce',
      'kurtce': 'Kürtçe',
      'hakkinda': 'Hakkında',
      'versiyon': 'Versiyon',
      'iletisim': 'İletişim',
      'nakliye_firmalari': 'Nakliye Firmaları',
      'firma_yok': 'Henüz firma yok.',
      'ilan_yok': 'Henüz ilan yok.',
      'mesaj_yok': 'Henüz mesaj yok.',
      'yukleniyor': 'Yükleniyor...',
      'hata': 'Hata',
      'tamam': 'Tamam',
      'iptal': 'İptal',
      'evet': 'Evet',
      'hayir': 'Hayır',
      'kaydet': 'Kaydet',
      'guncelle': 'Güncelle',
      'sil': 'Sil',
      'ekle': 'Ekle',
      'gonder': 'Gönder',
      'ara': 'Ara...',
      'deneme': 'Deneme',
      'deneme_suruyor': 'Deneme sürüyor',
      'deneme_bitti': 'Deneme bitti',
      'odeme_gerekli': 'Ödeme gerekli',
      'paketler': 'Paketler',
      'odeme_yap': 'Ödeme Yap',
      'aktivasyon_kodu': 'Aktivasyon Kodu',
      'kodu_gir': 'Kodu gir',
      'paket_aktif': 'Paket Aktif',
      'kalan_doping': 'Kalan Doping',
      'gun_kaldi': 'gün kaldı',
      'hos_geldiniz': "EENApp'a Hoş Geldiniz",
      'nasil_devam': 'Nasıl devam etmek istersiniz?',
      'musteri_giris': 'Müşteri Girişi / Kaydı',
      'nakliyeci_giris': 'Nakliyeci Girişi / Kaydı',
      'sizi_taniyalim': 'Sizi Yakından Tanıyalım',
      'sifre_sifirla': 'Şifre Sıfırla',
      'mail_gonder': 'Mail Gönder',
      'mail_gonderildi': 'Mail gönderildi!',
    },

    // ==================== İNGİLİZCE ====================
    'en': {
      'app_adi': 'EENApp',
      'alt_baslik': 'Freight Marketplace',
      'giris_yap': 'Login',
      'kayit_ol': 'Register',
      'cikis_yap': 'Logout',
      'hesabin_yok': "Don't have an account? Register",
      'hesabin_var': 'Already have an account? Login',
      'sifremi_unuttum': 'Forgot password',
      'email': 'Email',
      'sifre': 'Password',
      'sifre_tekrar': 'Password Repeat',
      'ad_soyad': 'Full Name / Company',
      'telefon': 'Phone',
      'hesap_turu': 'Account Type',
      'musteri': 'Customer',
      'nakliyeci': 'Carrier',
      'firmalar': 'Companies',
      'ilanlar': 'Listings',
      'mesajlar': 'Messages',
      'profil': 'Profile',
      'ayarlar': 'Settings',
      'gorunum': 'Appearance',
      'karanlik_tema': 'Dark Theme',
      'dil': 'Language',
      'turkce': 'Turkish',
      'ingilizce': 'English',
      'kurtce': 'Kurdish',
      'hakkinda': 'About',
      'versiyon': 'Version',
      'iletisim': 'Contact',
      'nakliye_firmalari': 'Transport Companies',
      'firma_yok': 'No companies yet.',
      'ilan_yok': 'No listings yet.',
      'mesaj_yok': 'No messages yet.',
      'yukleniyor': 'Loading...',
      'hata': 'Error',
      'tamam': 'OK',
      'iptal': 'Cancel',
      'evet': 'Yes',
      'hayir': 'No',
      'kaydet': 'Save',
      'guncelle': 'Update',
      'sil': 'Delete',
      'ekle': 'Add',
      'gonder': 'Send',
      'ara': 'Search...',
      'deneme': 'Trial',
      'deneme_suruyor': 'Trial active',
      'deneme_bitti': 'Trial ended',
      'odeme_gerekli': 'Payment required',
      'paketler': 'Plans',
      'odeme_yap': 'Make Payment',
      'aktivasyon_kodu': 'Activation Code',
      'kodu_gir': 'Enter code',
      'paket_aktif': 'Plan Active',
      'kalan_doping': 'Remaining Boost',
      'gun_kaldi': 'days left',
      'hos_geldiniz': 'Welcome to EENApp',
      'nasil_devam': 'How would you like to continue?',
      'musteri_giris': 'Customer Login / Register',
      'nakliyeci_giris': 'Carrier Login / Register',
      'sizi_taniyalim': "Let's Get to Know You",
      'sifre_sifirla': 'Reset Password',
      'mail_gonder': 'Send Mail',
      'mail_gonderildi': 'Mail sent!',
    },

    // ==================== KÜRTÇE ====================
    'ku': {
      'app_adi': 'EENApp',
      'alt_baslik': 'Bazara Veguhastinê',
      'giris_yap': 'Têkeve',
      'kayit_ol': 'Tomar Bike',
      'cikis_yap': 'Derkeve',
      'hesabin_yok': 'Hesabê te tune? Tomar bike',
      'hesabin_var': 'Hesabê te heye? Têkeve',
      'sifremi_unuttum': 'Şîfreya xwe ji bîr kir',
      'email': 'E-name',
      'sifre': 'Şîfre',
      'sifre_tekrar': 'Şîfre Dîsa',
      'ad_soyad': 'Nav Û Paşnav / Firma',
      'telefon': 'Telefon',
      'hesap_turu': 'Cureyê Hesab',
      'musteri': 'Xerîdar',
      'nakliyeci': 'Veguhêzer',
      'firmalar': 'Firmayên',
      'ilanlar': 'Reklam',
      'mesajlar': 'Peyam',
      'profil': 'Profil',
      'ayarlar': 'Mîheng',
      'gorunum': 'Xuyang',
      'karanlik_tema': 'Tema Tarî',
      'dil': 'Ziman',
      'turkce': 'Tirkî',
      'ingilizce': 'Îngilîzî',
      'kurtce': 'Kurdî',
      'hakkinda': 'Derbarê',
      'versiyon': 'Guherto',
      'iletisim': 'Têkilî',
      'nakliye_firmalari': 'Firmayên Veguhastinê',
      'firma_yok': 'Hêj firma tune.',
      'ilan_yok': 'Hêj reklam tune.',
      'mesaj_yok': 'Hêj peyam tune.',
      'yukleniyor': 'Tê barkirin...',
      'hata': 'Xeletî',
      'tamam': 'Baş e',
      'iptal': 'Betal',
      'evet': 'Erê',
      'hayir': 'Na',
      'kaydet': 'Tomar bike',
      'guncelle': 'Nûve bike',
      'sil': 'Jê bibe',
      'ekle': 'Zêde bike',
      'gonder': 'Bişîne',
      'ara': 'Lê bigere...',
      'deneme': 'Ceribandin',
      'deneme_suruyor': 'Ceribandin berdewam e',
      'deneme_bitti': 'Ceribandin qediya',
      'odeme_gerekli': 'Pere pêwîst e',
      'paketler': 'Pakêt',
      'odeme_yap': 'Pere bide',
      'aktivasyon_kodu': 'Koda Çalakkirinê',
      'kodu_gir': 'Kodê binivîse',
      'paket_aktif': 'Pakêt Çalak',
      'kalan_doping': 'Doping Dimîne',
      'gun_kaldi': 'roj mane',
      'hos_geldiniz': 'Bi xêr hatî EENApp',
      'nasil_devam': 'Tu dixwazî çawa bidomînî?',
      'musteri_giris': 'Têketina Xerîdar',
      'nakliyeci_giris': 'Têketina Veguhêzer',
      'sizi_taniyalim': 'Em te nas bikin',
      'sifre_sifirla': 'Şîfreyê Sifir Bike',
      'mail_gonder': 'E-name Bişîne',
      'mail_gonderildi': 'E-name hat şandin!',
    },
  };

  // Çeviri fonksiyonu
  static String cevir(String dil, String anahtar) {
    return _veri[dil]?[anahtar] ?? _veri['tr']?[anahtar] ?? anahtar;
  }
}

// ============================================================
// DİL YÖNETİCİSİ (Provider)
// ============================================================
class DilYoneticisi extends ChangeNotifier {
  String _dil = 'tr';

  String get dil => _dil;

  String cevir(String anahtar) {
    return Ceviriler.cevir(_dil, anahtar);
  }

  void dilDegistir(String yeniDil) {
    _dil = yeniDil;
    notifyListeners();
  }
}